/* Metal runtime — Objective-C++ implementation. Compiled with -fobjc-arc.
 *
 * On Apple Silicon, MTLBuffer with StorageModeShared lives in unified
 * memory: the same pointer is valid for both CPU code and GPU kernels.
 * No explicit synchronization needed for shared buffers within the same
 * MTLCommandBuffer's completion. */
#include "metal_runtime.h"

#import <Foundation/Foundation.h>
#import <Metal/Metal.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <string>
#include <unordered_map>

/* Generated by CMake's `xxd -i` step from src/metal/kernels.metal.
 * Provides:
 *   unsigned char ib_metal_kernels_src[];
 *   unsigned int  ib_metal_kernels_src_len;
 */
#include "kernels_metal_src.h"

struct ib_metal_ctx {
    id<MTLDevice>       device;
    id<MTLCommandQueue> queue;
    id<MTLLibrary>      library;
    /* Map from raw pointer (the .contents of MTLBuffer) → the MTLBuffer
     * itself. Keeps Obj-C objects alive while the user holds the C ptr. */
    std::unordered_map<void *, id<MTLBuffer>> buffers;
    /* Cached pipeline objects keyed by kernel name. */
    std::unordered_map<std::string, id<MTLComputePipelineState>> pipelines;
};

extern "C" int ib_metal_available(void) {
    @autoreleasepool {
        id<MTLDevice> dev = MTLCreateSystemDefaultDevice();
        return dev ? 1 : 0;
    }
}

extern "C" ib_metal_ctx *ib_metal_create(void) {
    @autoreleasepool {
        id<MTLDevice> dev = MTLCreateSystemDefaultDevice();
        if (!dev) {
            fprintf(stderr, "ib_metal_create: no Metal device\n");
            return NULL;
        }
        id<MTLCommandQueue> q = [dev newCommandQueue];
        if (!q) {
            fprintf(stderr, "ib_metal_create: failed to create command queue\n");
            return NULL;
        }

        /* Compile shader source at runtime. The Metal compiler is part
         * of macOS itself, so this works on any user machine without
         * Xcode. Apple caches compiled artifacts internally so the
         * second run of a process pays only ~5-50ms vs ~100-500ms cold. */
        NSString *src = [[NSString alloc] initWithBytes:ib_metal_kernels_src
                                                  length:ib_metal_kernels_src_len
                                                encoding:NSUTF8StringEncoding];
        if (!src) {
            fprintf(stderr, "ib_metal_create: failed to wrap kernel source\n");
            return NULL;
        }
        MTLCompileOptions *opts = [MTLCompileOptions new];
        /* Default optimization (Apple's compiler is good); disable fast-math
         * to keep numerical equivalence with CPU paths. */
        opts.fastMathEnabled = NO;
        NSError *err = nil;
        id<MTLLibrary> lib = [dev newLibraryWithSource:src options:opts error:&err];
        if (!lib) {
            fprintf(stderr, "ib_metal_create: shader compile failed: %s\n",
                    err ? [[err localizedDescription] UTF8String] : "n/a");
            return NULL;
        }

        ib_metal_ctx *ctx = new ib_metal_ctx();
        ctx->device = dev;
        ctx->queue  = q;
        ctx->library = lib;
        return ctx;
    }
}

extern "C" void ib_metal_destroy(ib_metal_ctx *ctx) {
    if (!ctx) return;
    @autoreleasepool {
        ctx->buffers.clear();
        ctx->pipelines.clear();
        ctx->device = nil;
        ctx->queue = nil;
        ctx->library = nil;
    }
    delete ctx;
}

extern "C" const char *ib_metal_device_name(ib_metal_ctx *ctx) {
    if (!ctx) return NULL;
    static thread_local char buf[256];
    @autoreleasepool {
        const char *name = [[ctx->device name] UTF8String];
        if (!name) return NULL;
        strncpy(buf, name, sizeof(buf) - 1);
        buf[sizeof(buf) - 1] = '\0';
    }
    return buf;
}

extern "C" void *ib_metal_alloc(ib_metal_ctx *ctx, size_t bytes, const void *init) {
    if (!ctx || bytes == 0) return NULL;
    @autoreleasepool {
        id<MTLBuffer> b = nil;
        if (init) {
            b = [ctx->device newBufferWithBytes:init length:bytes
                                          options:MTLResourceStorageModeShared];
        } else {
            b = [ctx->device newBufferWithLength:bytes
                                          options:MTLResourceStorageModeShared];
        }
        if (!b) return NULL;
        void *ptr = [b contents];
        ctx->buffers[ptr] = b;
        return ptr;
    }
}

extern "C" void ib_metal_free(ib_metal_ctx *ctx, void *buf) {
    if (!ctx || !buf) return;
    auto it = ctx->buffers.find(buf);
    if (it != ctx->buffers.end()) {
        ctx->buffers.erase(it);
    }
}

static id<MTLComputePipelineState> get_pipeline(ib_metal_ctx *ctx,
                                                   const char *fn_name) {
    auto it = ctx->pipelines.find(fn_name);
    if (it != ctx->pipelines.end()) return it->second;
    NSError *err = nil;
    id<MTLFunction> fn = [ctx->library newFunctionWithName:
                            [NSString stringWithUTF8String:fn_name]];
    if (!fn) {
        fprintf(stderr, "Metal: kernel '%s' not in metallib\n", fn_name);
        return nil;
    }
    id<MTLComputePipelineState> ps = [ctx->device newComputePipelineStateWithFunction:fn
                                                                                 error:&err];
    if (!ps) {
        fprintf(stderr, "Metal: pipeline '%s' failed: %s\n", fn_name,
                err ? [[err localizedDescription] UTF8String] : "n/a");
        return nil;
    }
    ctx->pipelines[fn_name] = ps;
    return ps;
}

extern "C" int ib_metal_vec_mul2(ib_metal_ctx *ctx,
                                   const void *gpu_in, void *gpu_out, int n) {
    if (!ctx || !gpu_in || !gpu_out || n <= 0) return -1;
    @autoreleasepool {
        id<MTLComputePipelineState> ps = get_pipeline(ctx, "vec_mul2");
        if (!ps) return -1;

        auto it_in  = ctx->buffers.find((void *)gpu_in);
        auto it_out = ctx->buffers.find(gpu_out);
        if (it_in == ctx->buffers.end() || it_out == ctx->buffers.end()) {
            fprintf(stderr, "Metal: pointer not registered with this ctx\n");
            return -1;
        }
        id<MTLBuffer> b_in  = it_in->second;
        id<MTLBuffer> b_out = it_out->second;

        id<MTLCommandBuffer> cb = [ctx->queue commandBuffer];
        id<MTLComputeCommandEncoder> enc = [cb computeCommandEncoder];
        [enc setComputePipelineState:ps];
        [enc setBuffer:b_in  offset:0 atIndex:0];
        [enc setBuffer:b_out offset:0 atIndex:1];

        NSUInteger tg = ps.maxTotalThreadsPerThreadgroup;
        if (tg > (NSUInteger)n) tg = (NSUInteger)n;
        MTLSize threads = MTLSizeMake((NSUInteger)n, 1, 1);
        MTLSize tgsize  = MTLSizeMake(tg, 1, 1);
        [enc dispatchThreads:threads threadsPerThreadgroup:tgsize];
        [enc endEncoding];

        [cb commit];
        [cb waitUntilCompleted];
        if (cb.status == MTLCommandBufferStatusError) {
            fprintf(stderr, "Metal vec_mul2: cmd buffer error: %s\n",
                    [[cb.error localizedDescription] UTF8String]);
            return -1;
        }
    }
    return 0;
}

extern "C" int ib_metal_quantize_input_int8_g128(ib_metal_ctx *ctx,
                                                    const void *x,
                                                    void *x_q, void *x_scales,
                                                    int N)
{
    if (!ctx || !x || !x_q || !x_scales || N <= 0) return -1;
    @autoreleasepool {
        id<MTLComputePipelineState> ps = get_pipeline(ctx, "quantize_input_int8_g128");
        if (!ps) return -1;
        auto pick = [&](const void *p) -> id<MTLBuffer> {
            auto it = ctx->buffers.find((void *)p);
            return it == ctx->buffers.end() ? nil : it->second;
        };
        id<MTLBuffer> b_x  = pick(x);
        id<MTLBuffer> b_xq = pick(x_q);
        id<MTLBuffer> b_xs = pick(x_scales);
        if (!b_x || !b_xq || !b_xs) {
            fprintf(stderr, "Metal quantize: buffer not registered with this ctx\n");
            return -1;
        }
        uint N_u = (uint)N;
        id<MTLCommandBuffer> cb = [ctx->queue commandBuffer];
        id<MTLComputeCommandEncoder> enc = [cb computeCommandEncoder];
        [enc setComputePipelineState:ps];
        [enc setBuffer:b_x  offset:0 atIndex:0];
        [enc setBuffer:b_xq offset:0 atIndex:1];
        [enc setBuffer:b_xs offset:0 atIndex:2];
        [enc setBytes:&N_u length:sizeof(N_u) atIndex:3];

        /* One threadgroup per group of 128 elements. 32 threads/TG
         * (one SIMD group), each handling 4 elements. */
        NSUInteger n_groups = (NSUInteger)((N + 127) / 128);
        MTLSize grid = MTLSizeMake(n_groups, 1, 1);
        MTLSize tgsize = MTLSizeMake(32, 1, 1);
        [enc dispatchThreadgroups:grid threadsPerThreadgroup:tgsize];
        [enc endEncoding];

        [cb commit];
        [cb waitUntilCompleted];
        if (cb.status == MTLCommandBufferStatusError) {
            fprintf(stderr, "Metal quantize: cmd buffer error: %s\n",
                    [[cb.error localizedDescription] UTF8String]);
            return -1;
        }
    }
    return 0;
}

extern "C" int ib_metal_matmul_w4a8_fp32_in(ib_metal_ctx *ctx,
                                              const void *x_fp32,
                                              const void *weights,
                                              const void *w_scales,
                                              void *out,
                                              void *scratch_x_q,
                                              void *scratch_x_scales,
                                              int M, int N)
{
    if (!ctx || !x_fp32 || !weights || !w_scales || !out) return -1;
    if (M <= 0 || N <= 0) return -1;

    @autoreleasepool {
        id<MTLComputePipelineState> ps_q  = get_pipeline(ctx, "quantize_input_int8_g128");
        id<MTLComputePipelineState> ps_mm = get_pipeline(ctx, "matmul_w4a8");
        if (!ps_q || !ps_mm) return -1;

        auto pick = [&](const void *p) -> id<MTLBuffer> {
            auto it = ctx->buffers.find((void *)p);
            return it == ctx->buffers.end() ? nil : it->second;
        };
        id<MTLBuffer> b_x   = pick(x_fp32);
        id<MTLBuffer> b_w   = pick(weights);
        id<MTLBuffer> b_ws  = pick(w_scales);
        id<MTLBuffer> b_out = pick(out);
        if (!b_x || !b_w || !b_ws || !b_out) {
            fprintf(stderr, "Metal fused: buffer not registered with ctx\n");
            return -1;
        }

        /* Allocate temp scratch if caller didn't provide. */
        int n_groups = (N + 127) / 128;
        bool own_xq = false, own_xs = false;
        id<MTLBuffer> b_xq, b_xs;
        if (scratch_x_q) {
            b_xq = pick(scratch_x_q);
        } else {
            b_xq = [ctx->device newBufferWithLength:(NSUInteger)N
                                              options:MTLResourceStorageModeShared];
            own_xq = true;
        }
        if (scratch_x_scales) {
            b_xs = pick(scratch_x_scales);
        } else {
            b_xs = [ctx->device newBufferWithLength:(NSUInteger)n_groups * sizeof(float)
                                              options:MTLResourceStorageModeShared];
            own_xs = true;
        }
        if (!b_xq || !b_xs) {
            fprintf(stderr, "Metal fused: scratch alloc failed\n");
            return -1;
        }

        /* Single command buffer with TWO encoders → one commit/wait. */
        uint M_u = (uint)M;
        uint N_u = (uint)N;
        id<MTLCommandBuffer> cb = [ctx->queue commandBuffer];

        /* Encoder 1: quantize_input_int8_g128 */
        id<MTLComputeCommandEncoder> enc1 = [cb computeCommandEncoder];
        [enc1 setComputePipelineState:ps_q];
        [enc1 setBuffer:b_x  offset:0 atIndex:0];
        [enc1 setBuffer:b_xq offset:0 atIndex:1];
        [enc1 setBuffer:b_xs offset:0 atIndex:2];
        [enc1 setBytes:&N_u length:sizeof(N_u) atIndex:3];
        {
            NSUInteger nq = (NSUInteger)((N + 127) / 128);
            [enc1 dispatchThreadgroups:MTLSizeMake(nq, 1, 1)
                  threadsPerThreadgroup:MTLSizeMake(32, 1, 1)];
        }
        [enc1 endEncoding];

        /* Encoder 2: matmul_w4a8 */
        id<MTLComputeCommandEncoder> enc2 = [cb computeCommandEncoder];
        [enc2 setComputePipelineState:ps_mm];
        [enc2 setBuffer:b_w   offset:0 atIndex:0];
        [enc2 setBuffer:b_ws  offset:0 atIndex:1];
        [enc2 setBuffer:b_xq  offset:0 atIndex:2];
        [enc2 setBuffer:b_xs  offset:0 atIndex:3];
        [enc2 setBuffer:b_out offset:0 atIndex:4];
        [enc2 setBytes:&M_u length:sizeof(M_u) atIndex:5];
        [enc2 setBytes:&N_u length:sizeof(N_u) atIndex:6];
        {
            const NSUInteger SIMDS_PER_TG = 4;
            const NSUInteger TG_THREADS = 32 * SIMDS_PER_TG;
            NSUInteger n_tg = (M + SIMDS_PER_TG - 1) / SIMDS_PER_TG;
            [enc2 dispatchThreadgroups:MTLSizeMake(n_tg, 1, 1)
                  threadsPerThreadgroup:MTLSizeMake(TG_THREADS, 1, 1)];
        }
        [enc2 endEncoding];

        /* ONE commit/wait for both kernels. */
        [cb commit];
        [cb waitUntilCompleted];

        if (cb.status == MTLCommandBufferStatusError) {
            fprintf(stderr, "Metal fused: cmd buffer error: %s\n",
                    [[cb.error localizedDescription] UTF8String]);
            if (own_xq) b_xq = nil;
            if (own_xs) b_xs = nil;
            return -1;
        }
        /* Caller-owned scratch isn't freed here; transient ARC handles ours. */
        (void)own_xq; (void)own_xs;
    }
    return 0;
}

extern "C" int ib_metal_matmul_w4a8(ib_metal_ctx *ctx,
                                      const void *weights, const void *w_scales,
                                      const void *x_q, const void *x_scales,
                                      void *out,
                                      int M, int N)
{
    if (!ctx || !weights || !w_scales || !x_q || !x_scales || !out) return -1;
    if (M <= 0 || N <= 0) return -1;
    @autoreleasepool {
        id<MTLComputePipelineState> ps = get_pipeline(ctx, "matmul_w4a8");
        if (!ps) return -1;

        auto pick = [&](const void *p) -> id<MTLBuffer> {
            auto it = ctx->buffers.find((void *)p);
            return it == ctx->buffers.end() ? nil : it->second;
        };
        id<MTLBuffer> b_w  = pick(weights);
        id<MTLBuffer> b_ws = pick(w_scales);
        id<MTLBuffer> b_xq = pick(x_q);
        id<MTLBuffer> b_xs = pick(x_scales);
        id<MTLBuffer> b_out = pick(out);
        if (!b_w || !b_ws || !b_xq || !b_xs || !b_out) {
            fprintf(stderr, "Metal matmul_w4a8: a buffer was not registered with this ctx\n");
            return -1;
        }

        uint M_u = (uint)M;
        uint N_u = (uint)N;

        id<MTLCommandBuffer> cb = [ctx->queue commandBuffer];
        id<MTLComputeCommandEncoder> enc = [cb computeCommandEncoder];
        [enc setComputePipelineState:ps];
        [enc setBuffer:b_w   offset:0 atIndex:0];
        [enc setBuffer:b_ws  offset:0 atIndex:1];
        [enc setBuffer:b_xq  offset:0 atIndex:2];
        [enc setBuffer:b_xs  offset:0 atIndex:3];
        [enc setBuffer:b_out offset:0 atIndex:4];
        [enc setBytes:&M_u length:sizeof(M_u) atIndex:5];
        [enc setBytes:&N_u length:sizeof(N_u) atIndex:6];

        /* Each output row is one SIMD group (32 threads).
         * Pack 4 SIMD groups per threadgroup → 128 threads/TG.
         * Total threadgroups = ceil(M / 4). */
        const NSUInteger SIMDS_PER_TG = 4;
        const NSUInteger TG_THREADS = 32 * SIMDS_PER_TG;
        NSUInteger n_groups = (M + SIMDS_PER_TG - 1) / SIMDS_PER_TG;
        MTLSize grid_groups = MTLSizeMake(n_groups, 1, 1);
        MTLSize tgsize      = MTLSizeMake(TG_THREADS, 1, 1);
        [enc dispatchThreadgroups:grid_groups threadsPerThreadgroup:tgsize];
        [enc endEncoding];

        [cb commit];
        [cb waitUntilCompleted];
        if (cb.status == MTLCommandBufferStatusError) {
            fprintf(stderr, "Metal matmul_w4a8: cmd buffer error: %s\n",
                    [[cb.error localizedDescription] UTF8String]);
            return -1;
        }
    }
    return 0;
}

extern "C" int ib_metal_rmsnorm_fp16(ib_metal_ctx *ctx,
                                       const void *x_fp32,
                                       const void *weight_fp16,
                                       void *out_fp32,
                                       int N, float eps)
{
    if (!ctx || !x_fp32 || !weight_fp16 || !out_fp32 || N <= 0) return -1;
    @autoreleasepool {
        id<MTLComputePipelineState> ps = get_pipeline(ctx, "rmsnorm_fp16");
        if (!ps) return -1;

        auto pick = [&](const void *p) -> id<MTLBuffer> {
            auto it = ctx->buffers.find((void *)p);
            return it == ctx->buffers.end() ? nil : it->second;
        };
        id<MTLBuffer> b_x   = pick(x_fp32);
        id<MTLBuffer> b_w   = pick(weight_fp16);
        id<MTLBuffer> b_out = pick(out_fp32);
        if (!b_x || !b_w || !b_out) {
            fprintf(stderr, "Metal rmsnorm: buffer not registered with ctx\n");
            return -1;
        }

        uint N_u = (uint)N;
        float eps_v = eps;
        id<MTLCommandBuffer> cb = [ctx->queue commandBuffer];
        id<MTLComputeCommandEncoder> enc = [cb computeCommandEncoder];
        [enc setComputePipelineState:ps];
        [enc setBuffer:b_x   offset:0 atIndex:0];
        [enc setBuffer:b_w   offset:0 atIndex:1];
        [enc setBuffer:b_out offset:0 atIndex:2];
        [enc setBytes:&N_u   length:sizeof(N_u)   atIndex:3];
        [enc setBytes:&eps_v length:sizeof(eps_v) atIndex:4];
        /* One threadgroup of 256 threads (8 SIMDs). */
        [enc dispatchThreadgroups:MTLSizeMake(1, 1, 1)
              threadsPerThreadgroup:MTLSizeMake(256, 1, 1)];
        [enc endEncoding];
        [cb commit];
        [cb waitUntilCompleted];

        if (cb.status == MTLCommandBufferStatusError) {
            fprintf(stderr, "Metal rmsnorm: cmd buffer error: %s\n",
                    [[cb.error localizedDescription] UTF8String]);
            return -1;
        }
    }
    return 0;
}

extern "C" int ib_metal_silu_mul(ib_metal_ctx *ctx,
                                   const void *gate_fp32,
                                   const void *up_fp32,
                                   void *out_fp32,
                                   int N)
{
    if (!ctx || !gate_fp32 || !up_fp32 || !out_fp32 || N <= 0) return -1;
    @autoreleasepool {
        id<MTLComputePipelineState> ps = get_pipeline(ctx, "silu_mul");
        if (!ps) return -1;
        auto pick = [&](const void *p) -> id<MTLBuffer> {
            auto it = ctx->buffers.find((void *)p);
            return it == ctx->buffers.end() ? nil : it->second;
        };
        id<MTLBuffer> b_gate = pick(gate_fp32);
        id<MTLBuffer> b_up   = pick(up_fp32);
        id<MTLBuffer> b_out  = pick(out_fp32);
        if (!b_gate || !b_up || !b_out) {
            fprintf(stderr, "Metal silu_mul: buffer not registered\n");
            return -1;
        }

        uint N_u = (uint)N;
        id<MTLCommandBuffer> cb = [ctx->queue commandBuffer];
        id<MTLComputeCommandEncoder> enc = [cb computeCommandEncoder];
        [enc setComputePipelineState:ps];
        [enc setBuffer:b_gate offset:0 atIndex:0];
        [enc setBuffer:b_up   offset:0 atIndex:1];
        [enc setBuffer:b_out  offset:0 atIndex:2];
        [enc setBytes:&N_u    length:sizeof(N_u) atIndex:3];

        const NSUInteger TG = 256;
        NSUInteger n_tg = ((NSUInteger)N + TG - 1) / TG;
        [enc dispatchThreadgroups:MTLSizeMake(n_tg, 1, 1)
              threadsPerThreadgroup:MTLSizeMake(TG, 1, 1)];
        [enc endEncoding];
        [cb commit];
        [cb waitUntilCompleted];
        if (cb.status == MTLCommandBufferStatusError) {
            fprintf(stderr, "Metal silu_mul: cmd buffer error: %s\n",
                    [[cb.error localizedDescription] UTF8String]);
            return -1;
        }
    }
    return 0;
}

extern "C" int ib_metal_rope_inplace(ib_metal_ctx *ctx,
                                       void *tensor_fp32,
                                       int n_heads, int head_dim,
                                       int pos, float theta)
{
    if (!ctx || !tensor_fp32 || n_heads <= 0 || head_dim <= 0) return -1;
    if (head_dim & 1) return -1;  /* RoPE pairs require even head_dim. */
    @autoreleasepool {
        id<MTLComputePipelineState> ps = get_pipeline(ctx, "rope_inplace");
        if (!ps) return -1;
        auto pick = [&](const void *p) -> id<MTLBuffer> {
            auto it = ctx->buffers.find((void *)p);
            return it == ctx->buffers.end() ? nil : it->second;
        };
        id<MTLBuffer> b_t = pick(tensor_fp32);
        if (!b_t) {
            fprintf(stderr, "Metal rope: buffer not registered\n");
            return -1;
        }
        uint nh = (uint)n_heads, hd = (uint)head_dim, p = (uint)pos;
        float th = theta;

        id<MTLCommandBuffer> cb = [ctx->queue commandBuffer];
        id<MTLComputeCommandEncoder> enc = [cb computeCommandEncoder];
        [enc setComputePipelineState:ps];
        [enc setBuffer:b_t  offset:0 atIndex:0];
        [enc setBytes:&nh   length:sizeof(nh) atIndex:1];
        [enc setBytes:&hd   length:sizeof(hd) atIndex:2];
        [enc setBytes:&p    length:sizeof(p)  atIndex:3];
        [enc setBytes:&th   length:sizeof(th) atIndex:4];

        const NSUInteger TG = 64;
        NSUInteger total = (NSUInteger)n_heads * (NSUInteger)(head_dim / 2);
        NSUInteger n_tg = (total + TG - 1) / TG;
        [enc dispatchThreadgroups:MTLSizeMake(n_tg, 1, 1)
              threadsPerThreadgroup:MTLSizeMake(TG, 1, 1)];
        [enc endEncoding];
        [cb commit];
        [cb waitUntilCompleted];
        if (cb.status == MTLCommandBufferStatusError) {
            fprintf(stderr, "Metal rope: cmd buffer error: %s\n",
                    [[cb.error localizedDescription] UTF8String]);
            return -1;
        }
    }
    return 0;
}
